import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "chaos-bounce": {
          "0%": { transform: "translateY(0) translateX(0) scale(1) rotate(0deg)" },
          "15%": { transform: "translateY(-120px) translateX(-60px) scale(1.3) rotate(45deg)" },
          "30%": { transform: "translateY(-80px) translateX(80px) scale(0.7) rotate(-90deg)" },
          "45%": { transform: "translateY(-150px) translateX(-40px) scale(1.1) rotate(180deg)" },
          "60%": { transform: "translateY(-60px) translateX(100px) scale(0.9) rotate(-45deg)" },
          "75%": { transform: "translateY(-130px) translateX(-80px) scale(1.2) rotate(270deg)" },
          "100%": { transform: "translateY(0) translateX(0) scale(1) rotate(360deg)" },
        },
        "violent-spin": {
          "0%": { transform: "rotate(0deg) scale(1)" },
          "25%": { transform: "rotate(180deg) scale(1.5)" },
          "50%": { transform: "rotate(360deg) scale(0.5)" },
          "75%": { transform: "rotate(540deg) scale(1.3)" },
          "100%": { transform: "rotate(720deg) scale(1)" },
        },
        "erratic-float": {
          "0%": { transform: "translateY(0) translateX(0) rotate(0deg)" },
          "20%": { transform: "translateY(-100px) translateX(80px) rotate(90deg)" },
          "40%": { transform: "translateY(-50px) translateX(-100px) rotate(-45deg)" },
          "60%": { transform: "translateY(-120px) translateX(60px) rotate(180deg)" },
          "80%": { transform: "translateY(-40px) translateX(-80px) rotate(-90deg)" },
          "100%": { transform: "translateY(0) translateX(0) rotate(360deg)" },
        },
        "shake-extreme": {
          "0%, 100%": { transform: "translateX(0) translateY(0) rotate(0deg)" },
          "10%": { transform: "translateX(-30px) translateY(-30px) rotate(-15deg)" },
          "20%": { transform: "translateX(30px) translateY(30px) rotate(15deg)" },
          "30%": { transform: "translateX(-40px) translateY(20px) rotate(-10deg)" },
          "40%": { transform: "translateX(40px) translateY(-20px) rotate(10deg)" },
          "50%": { transform: "translateX(-35px) translateY(-25px) rotate(-20deg)" },
          "60%": { transform: "translateX(35px) translateY(25px) rotate(20deg)" },
          "70%": { transform: "translateX(-25px) translateY(30px) rotate(-12deg)" },
          "80%": { transform: "translateX(25px) translateY(-30px) rotate(12deg)" },
          "90%": { transform: "translateX(-20px) translateY(20px) rotate(-8deg)" },
        },
        "zoom-crazy": {
          "0%, 100%": { transform: "scale(1) rotate(0deg)" },
          "25%": { transform: "scale(2) rotate(90deg)" },
          "50%": { transform: "scale(0.5) rotate(180deg)" },
          "75%": { transform: "scale(1.8) rotate(270deg)" },
        },
        "diagonal-rush": {
          "0%": { transform: "translate(-200%, -200%) rotate(0deg) scale(0)" },
          "50%": { transform: "translate(0, 0) rotate(360deg) scale(1.5)" },
          "100%": { transform: "translate(200%, 200%) rotate(720deg) scale(0)" },
        },
        "bounce-insane": {
          "0%, 100%": { transform: "translateY(0) scale(1)" },
          "10%": { transform: "translateY(-180px) scale(1.4)" },
          "20%": { transform: "translateY(-50px) scale(0.8)" },
          "30%": { transform: "translateY(-200px) scale(1.3)" },
          "40%": { transform: "translateY(-80px) scale(0.9)" },
          "50%": { transform: "translateY(-220px) scale(1.5)" },
          "60%": { transform: "translateY(-60px) scale(0.7)" },
          "70%": { transform: "translateY(-190px) scale(1.2)" },
          "80%": { transform: "translateY(-100px) scale(0.85)" },
          "90%": { transform: "translateY(-160px) scale(1.1)" },
        },
        "spiral-out": {
          "0%": { transform: "translate(0, 0) rotate(0deg) scale(1)" },
          "100%": { transform: "translate(200px, -200px) rotate(1080deg) scale(0.3)" },
        },
        "wobble-violent": {
          "0%, 100%": { transform: "skewX(0deg) skewY(0deg) rotate(0deg)" },
          "25%": { transform: "skewX(25deg) skewY(-25deg) rotate(15deg)" },
          "50%": { transform: "skewX(-25deg) skewY(25deg) rotate(-15deg)" },
          "75%": { transform: "skewX(20deg) skewY(-20deg) rotate(10deg)" },
        },
        "pulse-extreme": {
          "0%, 100%": { transform: "scale(1)", opacity: "1" },
          "25%": { transform: "scale(2.5)", opacity: "0.4" },
          "50%": { transform: "scale(0.3)", opacity: "1" },
          "75%": { transform: "scale(2)", opacity: "0.5" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "chaos-bounce": "chaos-bounce 1.5s ease-in-out infinite",
        "violent-spin": "violent-spin 2s ease-in-out infinite",
        "erratic-float": "erratic-float 2.5s ease-in-out infinite",
        "shake-extreme": "shake-extreme 0.5s ease-in-out infinite",
        "zoom-crazy": "zoom-crazy 1.2s ease-in-out infinite",
        "diagonal-rush": "diagonal-rush 3s linear infinite",
        "bounce-insane": "bounce-insane 1.8s ease-in-out infinite",
        "spiral-out": "spiral-out 4s linear infinite",
        "wobble-violent": "wobble-violent 0.8s ease-in-out infinite",
        "pulse-extreme": "pulse-extreme 1s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
